services:
  teamcity-server:
    image: jetbrains/teamcity-server
    container_name: teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - teamcity_server_data:/data/teamcity_server/datadir
      - teamcity_server_logs:/opt/teamcity/logs

  teamcity-agent:
    image: jetbrains/teamcity-agent
    container_name: teamcity-agent
    environment:
      - SERVER_URL=http://teamcity-server:8111
    depends_on:
      - teamcity-server
    volumes:
      - teamcity_agent_conf:/data/teamcity_agent/conf

volumes:
  teamcity_server_data:
  teamcity_server_logs:
  teamcity_agent_conf:
